
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# http:
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: voicerss
    api_key: !secret voicerss_api_key
    language: 'zh-hk'

group: !include include/groups.yaml
automation: !include include/automations.yaml
script: !include include/scripts.yaml
scene: !include include/scenes.yaml
device_tracker: !include include/device_trackers.yaml
light: !include include/lights.yaml
remote: !include include/remotes.yaml
switch: !include include/switches.yaml
homeassistant:
  customize: !include include/customize.yaml

frontend:
  themes: !include_dir_merge_named themes

browser_mod:
  prefix: "browser_mod_"
  devices:
    9d2461a7-1521d960:
      name: iPad_hub
    751db58f-78fe29b5:
      name: htc_e8_hub

lovelace:
  mode: yaml

  resources:
    - url: /browser_mod.js
      type: js
    - url: /hacsfiles/Homekit-panel-card/homekit-panel-card.js
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js?v=0.9.4
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js?v=1.11.0
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module

discovery:

homekit:
  filter:
    exclude_domains:
      - automation
      - device_tracker
      - input_boolean
    exclude_entities:
      - binary_sensor.updater
      - binary_sensor.yeelight_ceiling1_0x0000000007c50fc5_nightlight
      - binary_sensor.2_nightlight
      - binary_sensor.deng_3_nightlight
      - light.zou_lang_deng
      - light.ke_ting_deng_3
      - switch.wall_switch_a6b8_2
      - switch.wall_switch_a6b8
      - remote.ke_ting
      - media_player.ke_ting
      - light.ipad_hub
      - sensor.ipad_hub
      - media_player.ipad_hub
      - light.htc_e8_hub
      - sensor.htc_e8_hub
      - media_player.htc_e8_hub
      - switch.kiosk_mode
    exclude_entity_globs:
      - light.browser_mod_*
      - media_player.browser_mod_*
      - sensor.browser_mod_*
      
input_boolean:
  bedside_lamp:
    name: Check if bedside lamp is on

