kiosk_mode:
    
background: >-
  center / cover no-repeat fixed
  url('/hacsfiles/themes/ios-themes/5120x2880_pure_minimal_filtered.png')
title: HOME
views:
  - path: homekit
    title: HomeKit Panel
    icon: 'mdi:home-outline'
    panel: true
    badges: []
    cards:
      - type: 'custom:homekit-card'
        titleColor: '#FFFFFF'
        useBrightness: false
        useRGBColor: false
        statePositionTop: true
        enableColumns: true
        style: |
          :host {
            --tile-background: rgba(255, 255, 255, 0.8);
            --tile-border-radius: 18px;
            --tile-width: 100px;
            --tile-height: 100px;
            --tile-on-background: rgba(255, 255, 255, 1);

            --tile-name-text-color: rgba(0, 0, 0, 0.4);
            --tile-on-name-text-color: rgba(0, 0, 0, 1);

            --tile-state-text-color: rgba(0, 0, 0, 0.4);
            --tile-on-state-text-color: rgba(0, 0, 0, 1);

            --tile-state-changed-text-color: rgb(134, 134, 134);
            --tile-unavailable-state-text-color: rgba(255, 0, 0, 1);

            --tile-value-text-color: rgba(0, 0, 0, 1);


            --tile-icon-color: rgba(0, 0, 0, 0.3);
            --tile-on-icon-color: #F7CD47;


            --tile-width-mobile: 90px;
            --tile-height-mobile: 90px;

            --min-header-height: 150px;

            --tile-icon-size: 30px;

            --tile-image-radius: 100%

            --slider-width: 120px;
            --slider-height: 120px;
          }

          .button {
            box-shadow: none !important;
            font-weight: 400 !important;
          }

          .button.no-padding {
            width: 126px !important;
            height: 126px !important;          
          }

          .button.no-padding.size-2.height-2 {
            height: calc( (var(--tile-width, 100px) * 2) + (10px * 4) + (10px * 1) - 1px) !important;
            width: calc((var(--tile-width, 100px) * 2) + (10px * 4) + (10px * 1) - 1px) !important;
          }

          .button.event{
            padding: 13px !important;
          }

          .button-inner .icon {
            position: relative;
            left: -8px;
          }
          .circle-state path {
            stroke-width: 5;
            stroke: rgba(171, 171, 171, 0.9);
          }

          #count {
            font-size: 25px;
          }

          homekit-button[data-type="'custom'"] .name.on{
            margin-bottom: 15px;
          }

          homekit-button[data-type="'custom'"].height-half .name.on{
            margin-bottom: 0px;
          }

          @media only screen and (max-width: 768px) {
            .header, .homekit-card {
              width: 373px !important;
            }
          }

          .row {
            padding-top: 0px !important
          }

          @media only screen and (min-width: 769px) {
            .row .col.fixed {
              min-width: calc(var(--tile-on-row) * calc(var(--tile-width, 100px) + 34px)) !important;
              width: calc(var(--tile-on-row) * calc(var(--tile-width, 100px) + 34px)) !important;
            }       
          }
        rows:
          - row: 1
            columns:
              - column: 1
                tileOnRow: 2
                entities:
                  - title: 屋企
                    entities:
                      - entity: person.iammrandrew
                        name: 立仔
                      - entity: person.sis
                        name: 家姐
                      - entity: person.dad
                        name: 爸爸
                      - entity: person.mum
                        name: 媽咪
              - column: 2
                tileOnRow: 2
                entities:
                  - title: 電視
                    entities:
                      - entity: switch.tv
                        icon: 'mdi:television'
                        wider: true
                        # popup: 
                        #   title: 電視
                        #   type: entities
                        #   entities: 
                        #     - entity: switch.tv
                        #     - entity: script.tv_volume_up
                        #     - entity: script.tv_volume_down
                        #     - entity: script.tv_switch_av
                        #     - entity: script.tv_switch_tv
                        #   style: !include template/entity-card_style.yaml
                        hold_action:
                          action: call-service
                          service: browser_mod.popup
                          service_data:
                            title: ' '
                            deviceID: this
                            title: 電視
                            style: !include template/popup-card_style.yaml
                            card:
                              type: entities 
                              style: !include template/entity-card_style.yaml
                              entities: 
                                - entity: switch.tv
                                  icon: mdi:television
                                - entity: input_select.tv_source                                  
                                - type: custom:hui-element
                                  card_type: horizontal-stack
                                  cards:
                                  - type: custom:button-card
                                    entity: script.tv_volume_mute
                                    icon: mdi:volume-mute
                                    show_name: false
                                    style: !include template/button_style.yaml
                                  - type: custom:button-card
                                    entity: script.tv_volume_up
                                    icon: mdi:volume-medium
                                    show_name: false
                                    style: !include template/button_style.yaml
                                  - type: custom:button-card
                                    entity: script.tv_volume_down
                                    icon: mdi:volume-high
                                    show_name: false
                                    style: !include template/button_style.yaml
                                  - type: custom:button-card
                                    entity: script.tv_switch_av
                                    icon: mdi:import
                                    show_name: false
                                    style: !include template/button_style.yaml
                      - entity: media_player.ke_ting
                        wider: true
              - column: 3
                tileOnRow: 2
                entities:
                  - title: 影印機
                    entities:
                      - card: 'custom:mini-graph-card'
                        noPadding: true
                        wider: true
                        higher: true
                        cardOptions:
                          entities:
                            - entity: sensor.epson_wf_3520_series_black_ink
                              name: 黑色墨水
                              color: '#4B4B4B'
                            - entity: sensor.epson_wf_3520_series_magenta_ink
                              name: 紅色墨水
                              color: '#f15152'
                            - entity: sensor.epson_wf_3520_series_yellow_ink
                              name: 黃色墨水
                              color: '#ffd23f'
                            - entity: sensor.epson_wf_3520_series_cyan_ink
                              name: 藍色墨水
                              color: '#3a6ea5'
                          icon: 'mdi:printer'
                          name: 影印機
                          tap_action: none
                        cardStyle: !include template/mini-graph-card_cardStyle.yaml
                    
          - row: 2
            columns:
              - column: 1
                entities:
                  - title: 睡房
                    entities:
                      - entity: light.deng
                        icon: 'mdi:wall-sconce-flat'
                        popup:
                          type: 'custom:light-popup-card'
                          icon: 'mdi:wall-sconce-flat'
                          borderRadius: 30px;
                          sliderThumbColor: '#F2F2F2'
                          sliderTrackColor: '#F2F2F2'
                          actions:
                            - service: light.turn_on
                              service_data:
                                entity_id: light.deng
                                color_temp: 153 #6500K (10000000 / 5000)
                              color: 'rgb(255,248,254)'
                            - service: light.turn_on
                              service_data:
                                entity_id: light.deng
                                color_temp: 200
                              color: 'rgb(255,230,207)'
                            - service: browser_mod.popup
                              service_data:
                                title: ' '
                                deviceID: this
                                style: !include template/light-entity-card_style.yaml
                                card:
                                  type: custom:light-entity-card
                                  entity: light.deng
                                  brightness: false
                                  color_temp: true
                                  full_width_sliders: true
                                  show_slider_percent: true
                                  smooth_color_wheel: true
                                  consolidate_entities: true
                                  effects_list: false
                      - entity: light.mibedsidelamp2_5a9b
                        icon: 'mdi:lamp'
                        popup:
                          type: 'custom:light-popup-card'
                          icon: 'mdi:lamp'
                          borderRadius: 30px;
                          sliderThumbColor: '#F2F2F2'
                          sliderTrackColor: '#F2F2F2'
                          actions:
                            - service: light.turn_on
                              service_data:
                                entity_id: light.mibedsidelamp2_5a9b
                                rgb_color: [255,254,249]
                              color: 'rgb(255,254,249)'
                            - service: light.turn_on
                              service_data:
                                entity_id: light.mibedsidelamp2_5a9b
                                rgb_color: [255,238,230]
                              color: 'rgb(255,238,230)'
                            - service: browser_mod.popup
                              service_data:
                                title: ' '
                                deviceID: this
                                style: !include template/light-entity-card_style.yaml
                                card:
                                  type: custom:light-entity-card
                                  entity: light.mibedsidelamp2_5a9b
                                  brightness: false
                                  color_temp: true
                                  full_width_sliders: true
                                  show_slider_percent: true
                                  smooth_color_wheel: true
                                  consolidate_entities: true

                      - entity: alarm_control_panel.aqara_hub_a429
                      - entity: light.aqara_hub_a429
                        icon: 'mdi:alarm-light-outline'
                        popup:
                          type: 'custom:light-popup-card'
                          icon: 'mdi:alarm-light-outline'
                          borderRadius: 30px;
                          sliderThumbColor: '#F2F2F2'
                          sliderTrackColor: '#F2F2F2'

              - column: 2
                entities:
                  - title: 房間
                    popup:
                      type: 'custom:light-popup-card'
                      icon: 'mdi:wall-sconce-flat'
                      borderRadius: 30px;
                      sliderThumbColor: '#F2F2F2'
                      sliderTrackColor: '#F2F2F2'                      
                    entities:
                      - entity: light.deng_2
                        icon: 'mdi:wall-sconce-flat'
                        name: 主人房 燈
                        popupExtend:
                          actions:
                          - service: light.turn_on
                            service_data:
                              entity_id: light.deng_2
                              color_temp: 153 #6500K (10000000 / 5000)
                            color: 'rgb(255,248,254)'
                          - service: light.turn_on
                            service_data:
                              entity_id: light.deng_2
                              color_temp: 200 
                            color: 'rgb(255,230,207)'
                          - service: browser_mod.popup
                            service_data:
                              title: ' '
                              deviceID: this
                              style: !include template/light-entity-card_style.yaml
                              card:
                                type: custom:light-entity-card
                                entity: light.deng_2
                                brightness: false
                                color_temp: true
                                full_width_sliders: true
                                show_slider_percent: true
                                smooth_color_wheel: true
                                consolidate_entities: true
                                effects_list: false
                      - entity: light.deng_3
                        icon: 'mdi:wall-sconce-flat'
                        name: 睡房II 燈
                        popupExtend:
                          actions:
                          - service: light.turn_on
                            service_data:
                              entity_id: light.deng_3
                              color_temp: 153 #6500K (10000000 / 6500)
                            color: 'rgb(255,248,254)'
                          - service: light.turn_on
                            service_data:
                              entity_id: light.deng_3
                              color_temp: 200 
                            color: 'rgb(255,230,207)'
                          - service: browser_mod.popup
                            service_data:
                              title: ' '
                              deviceID: this
                              style: !include template/light-entity-card_style.yaml
                              card:
                                type: custom:light-entity-card
                                entity: light.deng_3
                                brightness: false
                                color_temp: true
                                full_width_sliders: true
                                show_slider_percent: true
                                smooth_color_wheel: true
                                consolidate_entities: true
                                effects_list: false
          - row: 3
            columns:
              - column: 1
                entities:
                  - title: 客廳
                    entities:
                      - entity: light.ke_ting_deng
                        icon: 'mdi:coach-lamp'
                        name: 客廳燈
                        popup:
                          type: 'custom:light-popup-card'
                          borderRadius: 30px;
                          icon: 'mdi:coach-lamp'
                          sliderThumbColor: '#F2F2F2'
                          sliderTrackColor: '#F2F2F2'
                      - entity: binary_sensor.iii_occupancy
                        icon: 'mdi:motion-sensor'
                        name: 動作偵測
                      - card: 'custom:mini-graph-card'
                        noPadding: true
                        cardOptions:
                          entities:
                            - sensor.iii_illuminance
                          icon: 'mdi:brightness-6'
                          name: 光照度
                        cardStyle: !include template/mini-graph-card_cardStyle.yaml
              - column: 2
                entities:
                  - title: 走廊
                    entities:
                      - entity: light.zou_lang_deng
                        icon: 'mdi:ceiling-light'
                        popup:
                          type: 'custom:light-popup-card'
                          borderRadius: 30px;
                          icon: 'mdi:ceiling-light'
                          sliderThumbColor: '#F2F2F2'
                          sliderTrackColor: '#F2F2F2'
                      - entity: binary_sensor.0x00158d0004480c67_occupancy
                        icon: 'mdi:motion-sensor'
                        name: 動作偵測
                      - card: 'custom:mini-graph-card'
                        noPadding: true
                        cardOptions:
                          entities:
                            - sensor.0x00158d0004480c67_illuminance
                          icon: 'mdi:brightness-6'
                          name: 光照度
                        cardStyle: !include template/mini-graph-card_cardStyle.yaml
          - row: 4
            columns:
              - column: 1
                entities:
                  - title: 其他
                    entities:
                      - entity: media_player.firehd8_hub
                        wider: true
                      - entity: switch.kiosk_mode
                        icon: 'mdi:tablet'
                        name: 切換 Kiosk 模式

