- platform: group
  name: 走廊燈
  entities:
  - light.lightbulb_6983
  - light.lightbulb_aab5
  
- platform: switch
  name: 客廳燈1
  entity_id: switch.living_room_lights_switch_left
  
- platform: switch
  name: 客廳燈2
  entity_id: switch.living_room_lights_switch_right
  
- platform: group
  name: 客廳燈
  entities:
  - light.ke_ting_deng_1
  - light.ke_ting_deng_2